version: '3.8'

services:
  netdiag-api:
    build: .
    container_name: netdiag-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: diagnostics_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      FLASK_APP: app
      FLASK_ENV: development
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: netdiag-db
    restart: always
    environment:
      POSTGRES_DB: diagnostics_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./netDiag-api/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  pgdata:
